### ISSUE TITLE
Feature request - entries field

### ISSUE THREAD

**Issue by joepagan** [mmikkel/Reasons-Craft#21]
Hey mmikkel,

Great plugin, though would be really useful if entries field was available. Example: Show this field if entry 43 is selected (or one of it's children).

**Comment by mmikkel** [comment]
Hello @lexbi, thanks for the nice words and input.

I definitely see the use case for relational fields (Entries, Categories, Tags, Assets and Users), and I've been thinking about it. It could be solved quite nicely by using a "Add entry" button (which would fire up an element selector modal, identical to the way the Entries field works inside an editing form) for the toggle fields' value inside the conditional builder.

Exactly how the condition "or one of its children" should be implemented, I'm less certain of. I guess having additional operators for the relational fields could be one way to do it, i.e. "If (entries field) (contains / contains children of / does not contain / does not contain children of / is equal to / is not equal to) (element select)".

Another issue to consider is dealing with multiple _locales_, which could be can of worms.

Anyway, having relational fields are complex and having them as toggle fields quickly gets a bit complex as well – I'm not convinced it'd be worth the effort, which is why I've put it off for now. But never say never :)

**Comment by joepagan** [comment]
Haha, cheers for getting back to me, yeah I can certainly see how tricky it could get. I think only in some cases I've wanted to show some fields only if a particular entry has been selected in an entries field, but, mostly I just want to show some more if it's populated at all. Another similar one: if an assets field is populated... 

I'm sure you've got loads of ideas and I'm just re-going over them.

I do hope to see all of this, though I understand there's not a great demand for them :D

**Comment by mmikkel** [comment]
Hey @lexbi – actually, enabling all fieldtypes (including relational ones like Entries) to at least have conditionals based on a null/not null value isn't such a bad idea, and should be fairly easy to implement (Matrix may be the exception, though...). Thanks for the idea!

**Comment by joepagan** [comment]
Ooo that would be awesome if it's not too difficult! 

Regarding the matrix thing, maybe if the matrix field has more than 1 row? I haven't really delved into plugin development that much so can't help you with that. sry :(

**Comment by theskyfloor** [comment]
I would love that the null/not null value check - could have used that on a date field just this week!

**Comment by mmikkel** [comment]
[Reasons 1.0.5](https://github.com/mmikkel/Reasons-Craft/releases/tag/v.1.0.5) adds all built-in relational fieldtypes (Entries, Assets, Categories, Tags and Users) as toggle fields, with simple empty/not empty (or null, not null) statements. I'm closing this issue as it's unlikely that I'll ever add _complex_ conditionals to relational fields (i.e. _display this field if entry ID 4546 is selected). Thanks for contributing!

**Comment by joepagan** [comment]
Awesome I'll give it a go, thanks for putting the work in 👍
