### ISSUE TITLE
Doesn't work with Craft Commerce

### ISSUE THREAD

**Issue by gazsp** [mmikkel/Reasons-Craft#26]
Is it possible to get this working with Craft Commerce?

The 'Manage conditionals' menu item doesn't show up when customising fields in Product Types in the  Commerce plugin.

**Comment by mmikkel** [comment]
Hello @gazsp, thanks for contributing. It's probably possible, though I couldn't give you an ETA.

**Comment by gazsp** [comment]
No worries. If you point me in the direction of where to look in the source (if you know of the top of your head), I might be able to sort it myself and do a PR.

If not, I'll keep watching the issue.

Thanks!

**Comment by mmikkel** [comment]
Hello @gazsp – so I did a little digging. The problem with Commerce is _variants_; essentially, Commerce products (can) have two field layouts at once, which Reasons isn't designed for – meaning I'll either have to refactor parts of the code, or write a custom Commerce handler. Also, variants work sort of like Matrix, which is also a problem currently. Not saying it's not going to happen, but it's probably going to take a little while :)

I love PRs, but I'm not sure how to point you in one direction or the other. Due to the problems outlined above, it's basically going to require some refactoring and/or development in all parts of the code.

**Comment by gazsp** [comment]
@mmikkel Cool, thanks for the info - sounds like a decent chunk of work.

I might have a look when I get some time, but it sounds like you'd be able to sort it more easily than me.

**Comment by madebyshape** [comment]
+1 for this problem.

It's a shame Commerce doesn't use the same field layout structure as it does normally.

**Comment by mmikkel** [comment]
Yeah – as stated previously I'd love to add Matrix and Commerce support, but I just haven't been able to find the time thus far :)

**Comment by madebyshape** [comment]
Yeah, I can wait really, I know the feeling of finding time! I'm not pushing :)
