### ISSUE TITLE
Support for Solspace Calendar 1.8.0

### ISSUE THREAD

**Issue by zizther** [mmikkel/Reasons-Craft#32]
It appears something has changed and Reasons no longer works with the latest version of Solspace Calendar (1.8.0 as of writing).

**Comment by darren131** [comment]
Any updates on this... Not seeing any of the condition options on the Calendars field set up section...
https://www.dropbox.com/s/9j87bwjpxpcnnkf/Screenshot%202017-06-14%2015.32.16.png?dl=0

**Comment by mmikkel** [comment]
Hi @zizther and @darren131 – I haven't investigated this one yet, but I think this is worth fixing, even if I've [officially ended development on Reasons](https://github.com/mmikkel/Reasons-Craft/wiki/Statement-on-Reasons-2,-Matrix-and-Craft-3). Hopefully it's a minor thing to mend – look for a patch fairly soon :)

**Comment by mmikkel** [comment]
Hi @zizther and @darren131 – turns out Solspace redesigned their Calendar plugin in v. 1.7.0 to have individual field layouts for each calendar, whereas it used a single one (similar to how Users work in Craft proper) in earlier versions. No wonder it broke (and as early as 1.7.0, not 1.8.0). 

In any case, [Reasons v. 1.0.9 ](https://github.com/mmikkel/Reasons-Craft/releases/tag/v.1.0.9)should have things sorted. Cheers!

**Comment by zizther** [comment]
@mmikkel appreciate the support on this one, being that Reasons has retired.
This is very helpful and allows me to keep things looking good when working with Calendar.

Thanks again!

**Comment by mmikkel** [comment]
@zizther I appreciate that, thanks. Actually the memo should read "_active_ development is retired" – I'll continue fixing current functionality if it breaks for as long as its feasible. I do use Reasons in Craft 2 builds myself, so it should/needs to keep working for the duration of 2's lifespan (the big caveat being if the CP should receive another big redesign, but I'm guessing that won't happen before 3 drops).
